name: Shoptopia
main: solar.rpg.shoptopia.Main
version: 1.1
depend: [Skyblock, Vault]
commands:
   shop:
      description: Shoptopia command.
      usage: /<command> <info/reload/create/update/remove>